version: "3"
services:
  jupyterlab:
    container_name: jupyterlab
    image: ghcr.io/maastrichtu-ids/jupyterlab-on-openshift
    restart: unless-stopped
    # user: "1000"
    # user: root
    # user: ${UID}
    ports:
      - 8888:8888
    volumes:
      - ./data/jupyterlab:/home/jovyan
    environment:
      - JUPYTER_TOKEN=password
      # - GRANT_SUDO=yes
