version: "3"
services:
  jupyterlab:
    container_name: jupyterlab
    image: ghcr.io/maastrichtu-ids/jupyterlab:latest
    restart: unless-stopped
    # user: "1000"
    user: root
    # user: ${UID}
    ports:
      - 8888:8888
    volumes:
      # Share your local nanopub keys to login auto with the Nanobench
      - ${HOME}/.nanopub:/home/jovyan/.nanopub
      # Share volumes for jupyterlab and openrefine:
      # - ./data/work:/home/jovyan/work
      # - ./data/openrefine:/home/jovyan/openrefine
    ## Without password:
    # command: "--NotebookApp.token=''"
    command: "--ServerApp.token=''"
    ## With password:
    # environment:
    #   - JUPYTER_TOKEN=password
