version: "3"
services:
  jupyterlab:
    container_name: jupyterlab
    image: ghcr.io/maastrichtu-ids/jupyterlab
    restart: unless-stopped
    # user: "1000"
    user: root
    # user: ${UID}
    ports:
      - 8888:8888
    volumes:
      - ./data/jupyterlab:/home/jovyan/work
      # Share your local nanopub keys to login auto with the Nanobench
      - ~/.nanopub:~/.nanopub
    ## Without password:
    command: "--NotebookApp.token=''"
    ## With password:
    # environment:
    #   - JUPYTER_TOKEN=password
